// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/stat.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatEmpty) Reset()         { *m = StatEmpty{} }
func (m *StatEmpty) String() string { return proto.CompactTextString(m) }
func (*StatEmpty) ProtoMessage()    {}
func (*StatEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_stat_e69b055b96e0e20f, []int{0}
}
func (m *StatEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatEmpty.Unmarshal(m, b)
}
func (m *StatEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatEmpty.Marshal(b, m, deterministic)
}
func (dst *StatEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatEmpty.Merge(dst, src)
}
func (m *StatEmpty) XXX_Size() int {
	return xxx_messageInfo_StatEmpty.Size(m)
}
func (m *StatEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_StatEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_StatEmpty proto.InternalMessageInfo

type ViewResponse struct {
	Active               []string `protobuf:"bytes,1,rep,name=active,proto3" json:"active,omitempty"`
	Passive              []string `protobuf:"bytes,2,rep,name=passive,proto3" json:"passive,omitempty"`
	From                 string   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	App                  int32    `protobuf:"varint,4,opt,name=app,proto3" json:"app,omitempty"`
	Hops                 int32    `protobuf:"varint,5,opt,name=hops,proto3" json:"hops,omitempty"`
	Waste                int32    `protobuf:"varint,6,opt,name=waste,proto3" json:"waste,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewResponse) Reset()         { *m = ViewResponse{} }
func (m *ViewResponse) String() string { return proto.CompactTextString(m) }
func (*ViewResponse) ProtoMessage()    {}
func (*ViewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stat_e69b055b96e0e20f, []int{1}
}
func (m *ViewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewResponse.Unmarshal(m, b)
}
func (m *ViewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewResponse.Marshal(b, m, deterministic)
}
func (dst *ViewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewResponse.Merge(dst, src)
}
func (m *ViewResponse) XXX_Size() int {
	return xxx_messageInfo_ViewResponse.Size(m)
}
func (m *ViewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ViewResponse proto.InternalMessageInfo

func (m *ViewResponse) GetActive() []string {
	if m != nil {
		return m.Active
	}
	return nil
}

func (m *ViewResponse) GetPassive() []string {
	if m != nil {
		return m.Passive
	}
	return nil
}

func (m *ViewResponse) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ViewResponse) GetApp() int32 {
	if m != nil {
		return m.App
	}
	return 0
}

func (m *ViewResponse) GetHops() int32 {
	if m != nil {
		return m.Hops
	}
	return 0
}

func (m *ViewResponse) GetWaste() int32 {
	if m != nil {
		return m.Waste
	}
	return 0
}

func init() {
	proto.RegisterType((*StatEmpty)(nil), "hashicorp.hyparview.example.stat.StatEmpty")
	proto.RegisterType((*ViewResponse)(nil), "hashicorp.hyparview.example.stat.ViewResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatClient is the client API for Stat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatClient interface {
	View(ctx context.Context, in *StatEmpty, opts ...grpc.CallOption) (*ViewResponse, error)
}

type statClient struct {
	cc *grpc.ClientConn
}

func NewStatClient(cc *grpc.ClientConn) StatClient {
	return &statClient{cc}
}

func (c *statClient) View(ctx context.Context, in *StatEmpty, opts ...grpc.CallOption) (*ViewResponse, error) {
	out := new(ViewResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.hyparview.example.stat.Stat/View", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatServer is the server API for Stat service.
type StatServer interface {
	View(context.Context, *StatEmpty) (*ViewResponse, error)
}

func RegisterStatServer(s *grpc.Server, srv StatServer) {
	s.RegisterService(&_Stat_serviceDesc, srv)
}

func _Stat_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.hyparview.example.stat.Stat/View",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatServer).View(ctx, req.(*StatEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Stat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hashicorp.hyparview.example.stat.Stat",
	HandlerType: (*StatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "View",
			Handler:    _Stat_View_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/stat.proto",
}

func init() { proto.RegisterFile("proto/stat.proto", fileDescriptor_stat_e69b055b96e0e20f) }

var fileDescriptor_stat_e69b055b96e0e20f = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xcd, 0x4a, 0xc4, 0x40,
	0x10, 0x84, 0x8d, 0xf9, 0x59, 0xd2, 0x7a, 0x58, 0x1a, 0x91, 0xc1, 0x53, 0xc8, 0x29, 0x20, 0x8c,
	0xa0, 0x6f, 0x20, 0xf8, 0x02, 0x11, 0x3c, 0x78, 0x6b, 0x97, 0x96, 0x04, 0x8c, 0xd3, 0xcc, 0x34,
	0x1b, 0xf7, 0x2d, 0x7c, 0x64, 0x99, 0xf6, 0x07, 0x6f, 0x7b, 0x9a, 0xaf, 0xba, 0xea, 0x50, 0x35,
	0xb0, 0x95, 0x18, 0x34, 0xdc, 0x24, 0x25, 0xf5, 0x86, 0xd8, 0x4d, 0x94, 0xa6, 0x79, 0x17, 0xa2,
	0xf8, 0xe9, 0x20, 0x14, 0xf7, 0x33, 0xaf, 0x9e, 0x3f, 0x68, 0x91, 0x37, 0xf6, 0x39, 0xd7, 0x9f,
	0x41, 0xfb, 0xa8, 0xa4, 0x0f, 0x8b, 0xe8, 0xa1, 0xff, 0x2c, 0xe0, 0xfc, 0x69, 0xe6, 0x75, 0xe4,
	0x24, 0xe1, 0x3d, 0x31, 0x5e, 0x42, 0x43, 0x3b, 0x9d, 0xf7, 0xec, 0x8a, 0xae, 0x1c, 0xda, 0xf1,
	0x47, 0xa1, 0x83, 0x8d, 0x50, 0x4a, 0xd9, 0x38, 0x35, 0xe3, 0x57, 0x22, 0x42, 0xf5, 0x1a, 0xc3,
	0xe2, 0xca, 0xae, 0x18, 0xda, 0xd1, 0x18, 0xb7, 0x50, 0x92, 0x88, 0xab, 0xba, 0x62, 0xa8, 0xc7,
	0x8c, 0x39, 0x35, 0x05, 0x49, 0xae, 0xb6, 0x93, 0x31, 0x5e, 0x40, 0xbd, 0x52, 0x52, 0x76, 0x8d,
	0x1d, 0xbf, 0xc5, 0xed, 0x02, 0x55, 0xee, 0x87, 0x0c, 0x55, 0x6e, 0x86, 0xd7, 0xfe, 0xd8, 0x24,
	0xff, 0xb7, 0xe7, 0xca, 0x1f, 0x0f, 0xff, 0x9f, 0xdb, 0x9f, 0xdc, 0x6f, 0x9e, 0x6b, 0xfb, 0xb9,
	0x97, 0xc6, 0x9e, 0xbb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xfe, 0x70, 0xfa, 0x54, 0x01,
	0x00, 0x00,
}
